# Create Arrays  
# Multidimentional Arrays  
# Randomly Generate Arrays  
# Element Wise Operations  
# Logical Operations  
# Summarizing Operations  

In [2]:
import numpy as np

In [3]:
np

<module 'numpy' from '/usr/local/python/3.12.1/lib/python3.12/site-packages/numpy/__init__.py'>

# Create Arrays #

In [4]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [5]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [6]:
np.full(10, 6.7)

array([6.7, 6.7, 6.7, 6.7, 6.7, 6.7, 6.7, 6.7, 6.7, 6.7])

In [7]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [8]:
a[2]

np.int64(3)

In [9]:
a[2] = 10

In [10]:
a

array([ 1,  2, 10,  4,  5])

In [11]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [13]:
np.linspace(0,1,11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

# Multi Dimensional Arrays #

In [17]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [18]:
np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Randomly Generated Arrays #

In [22]:
np.random.seed(2)
np.random.rand(5,2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [23]:
np.random.seed(2)
np.random.randn(5,2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [24]:
np.random.seed(2)
np.random.randint(low=0, high=100, size=(5,2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

# Element Wise Operations #

In [25]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [26]:
a+1

array([1, 2, 3, 4, 5])

In [32]:
b = (10 + (a*2)) ** 2
b

array([100, 144, 196, 256, 324])

In [33]:
a + b

array([100, 145, 198, 259, 328])

# Comparision Operators #

In [34]:
a

array([0, 1, 2, 3, 4])

In [35]:
a >= 2

array([False, False,  True,  True,  True])

In [36]:
a > b

array([False, False, False, False, False])

# Summarizing Operations #