Create Arrays
Multidimentional Arrays
Randomly Generate Arrays
Element Wise Operations
Logical Operations
Summarizing Operations

In [3]:
import numpy as np

In [4]:
np

<module 'numpy' from '/usr/local/python/3.12.1/lib/python3.12/site-packages/numpy/__init__.py'>

Create Arrays

In [5]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [6]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [7]:
np.full(10, 6.7)

array([6.7, 6.7, 6.7, 6.7, 6.7, 6.7, 6.7, 6.7, 6.7, 6.7])

In [12]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [13]:
a[2]

np.int64(3)

In [14]:
a[2] = 10

In [15]:
a

array([ 1,  2, 10,  4,  5])

In [16]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [18]:
np.linspace(0,1,11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

Multi Dimensional Arrays